### ISSUE TITLE
htmlMinify too aggressive, removes endtags

### ISSUE THREAD

**Issue by bbottema** [vladimmi/gulp-js-html-inject#2]
For empty end tags or implicit endings (`<tag></tag>` or `<tag />`), _htmlMinify_ tends to remove the ending, resulting in a missing end-tag (`<tag>` in both cases).

Does htmlMinify have options to turn off this behavior and is it possible to expose this option somehow in hulp-js-html-inject? Right now it is too aggressive.

**Comment by bbottema** [comment]
It should be _keepClosingSlash_, which is turned off by default. Either have it turned on by default by gulp-js-html-inject, or allow it to be changed through config on gulp-js-html-inject.

**Comment by vladimmi** [comment]
Turned this option on as I personally cant see any real file size saving or some unwanted effects to ever disable this or be able to change via config. Maybe you know one?

**Comment by bbottema** [comment]
Not really, but it helps them with their fancy benchmark bragging rights. Imagine a serious page with 200-300 tags. Might save 50 bytes or so? Not very practical for us though.

**Comment by vladimmi** [comment]
Yes, that's why I believe it's safe to be just set to true in code.

**Comment by bbottema** [comment]
I tried with the new settings and although there is improvement, it's still removing end tags of `<meta>` even if there is content inside. The minifier is a little opinionated it seems. I have not yet found a setting that will fix this aggressive refactoring.

Basically I'm only interested in having all newlines removed from the source code, nothing else.

After diving into the HTML minifier code, it seems it's parsing the HTML into a HTML 4.01 tree which states ['meta' tags should be empty](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L55). Unfortunately, HTML meta tags for other purposes (for example EPUB content) do allow for content. I don't think the minifier is a good match for gulp-js-html-inject.

**Comment by bbottema** [comment]
What about this instead? Or as an alternative setting?

https://www.npmjs.com/package/newline-remove

It's rather simple, but might just work. I already forked a branch to do an early test release for myself. I'll try with newline-remove and see how it works out.

**Comment by vladimmi** [comment]
Ok, I'll check it out to see if something can be changed. Can you please provide some tiny html code that is broken after using minifier to do tests?

My initial goal was to try to pack some large js project into single file (well, two - .js and .css) compressed as much as possible - that's why html minifier used when injecting html templates into scripts (to remove spaces, newlines, make attributes compact, etc). Then scripts itself are minified and compressed later at gulp.

On other side, just remove all newlines can broke html too - for example, they are important inside pre tags.

**Comment by bbottema** [comment]
Very true.

Here's what I used: https://kangax.github.io/html-minifier/.
Just paste the code below and play with the settings.

``` HTML
<meta>{{data}}</meta>
```

**Comment by bbottema** [comment]
I just tested with [gulp-js-html-inject-tmp v1.0.0](https://www.npmjs.com/package/gulp-js-html-inject-tmp) which uses only _newline-remove_. It works perfectly for my use case.

I do agree it will break `<pre>` tags. Not sure how to deal with that. Although it would be possible to replace all `<pre>.*?</pre>` blocks from the result with matching blocks from the source in the same order. A little bit expensive regex operation, but HTML files shouldn't be shattering large to handle.

However, how do you propose to concatenate `<pre>` blocks in a javascript variable? This doesn't work right now either, I guess.

**Comment by vladimmi** [comment]
Yes, html-minifier correctly leaves newlines as-is inside `<pre>`. I think it's maybe possible to make a fork of html-minifier and just move `<meta>` from `empty` list to another one to stop parser thinking it must be empty...

**Comment by vladimmi** [comment]
Or even better - make some additional option for this to remain old behavior for "true" html where meta is really empty

**Comment by bbottema** [comment]
I'm not a fan of forking HTML minifier, we'll have to manually keep it synced with the original if we want patches from that. Also, I'm note sure it entirely solves the issue. I found out about `<meta>`, but I don't know what I missed.

Either gulp-js-html-inject should properly focus on a HTML standard as it does now (4.01, by virtue of HTML minifier), in which case it is not a match for my use case, or it should be a general purpose HTML injector.

Perhaps I should simply fork this project into gulp-js-utf8-inject and just apply the remove-newline plugin.

**Comment by bbottema** [comment]
Actually your version has an issue with newlines as well as you are not escaping newlines. Or does HTML minifier return a string with escaped `\n` characters?

**Comment by vladimmi** [comment]
Sure, you are welcome to use and modify it as you find useful for you :)

About newlines - I've did this some months ago and possibly not checked all cases as had no real-world usage... Thanks for pointing so many mistakes, gonna fix them.

Btw, EPUB format seems to use the same HTML standard as browsers - is it really normal to place content inside `meta` tags?

As for me, I'll also check minifier more detailed now to be sure there are no other tags broken in usual HTML code. Other way I guess I'll think about switching to something simple and less oriented on HTML4 standard (hey, HTML5 is already here for a long time, actually) - like some arbitrary XML minifier with just several exceptions for `pre`, `script` and maybe other specific tags.

**Comment by bbottema** [comment]
Here's what I did that works for me and preserves `<pre>` formatting. It's rather simple, but I don't think you like it much :)

``` javascript
//filecontents = htmlMinify(filecontents, {
//                            removeComments: true,
//                            collapseWhitespace: true,
//                            keepClosingSlash: true
//                        });

//filecontents = removeNewline(filecontents);

filecontents = filecontents.replace(/\n/g, '\\n');
```

This puts it on a single line without breaking newlines. But minifiying is a little complicated.

**Comment by bbottema** [comment]
Regarding HTML in EPUB,

Here's the `<meta>` tag definition it uses: http://www.idpf.org/epub/30/spec/epub30-publications.html#elemdef-meta

I don't understand it completely, but it seems the EPUB Package Metadata Vocabulary uses the HTML5 syntax spec. Not sure what it means for `<meta>` having content.

**Comment by vladimmi** [comment]
Hmm, so I've read incorrect information and EPUB not just incapsulates HTML but has own XML-based format that is incompatible to HTML in some ways - EPUB meta should be not empty while HTML meta should be only empty and hold data in attributes. Looks like aggressive HTML minifier is really not for you this way...

**Comment by bbottema** [comment]
EPUB content can contain HTML5, the other files are a sort of DDL subset of HTML or something. 
Anyway, I think you're right, I think I'm going to fork your project into gulp-js-text-inject and also I will be needing a gulp-js-base64-inject so I can embed binary data as well.

Thank you for your time, however :)
